export enum FORGOTTEN_PASSWORD {
    EMAIL = 'FORGOTTEN_PASSWORD.EMAIL',
    INSTRUCTIONS_1 = 'FORGOTTEN_PASSWORD.INSTRUCTIONS_1',
    INSTRUCTIONS_2 = 'FORGOTTEN_PASSWORD.INSTRUCTIONS_2',
    BACK = 'FORGOTTEN_PASSWORD.BACK',
    VERIFY = 'FORGOTTEN_PASSWORD.VERIFY'
}