export enum LOGIN {
    TITLE = 'LOGIN.TITLE',
    USER = 'LOGIN.USER',
    USER_EXAMPLE = 'LOGIN.USER_EXAMPLE',
    PASS = 'LOGIN.PASS',
    MIN_PASS = 'LOGIN.MIN_PASS',
    FORGOT_PASS = 'LOGIN.FORGOT_PASS',
    REGISTER = 'LOGIN.REGISTER',
    CAPS_LOCKED_ON = 'LOGIN.CAPS_LOCKED_ON',
    EMAIL_ERROR = 'LOGIN.EMAIL_ERROR'
}