export enum REGISTER {
    REGISTER = 'REGISTER.REGISTER',
    COMPANY = 'REGISTER.COMPANY',
    COMPANY_PLACE = 'REGISTER.COMPANY_PLACE',
    USER = 'REGISTER.USER',
    USER_PLACE = 'REGISTER.USER_PLACE',
    PASS = 'REGISTER.PASS',
    MIN_PASS = 'REGISTER.MIN_PASS',
    COUNTRY = 'REGISTER.COUNTRY',
    COUNTRY_DROPDOWN = 'REGISTER.COUNTRY_DROPDOWN',
    SELFEMPLOYED = 'REGISTER.SELFEMPLOYED',
    ACC_TYPE = 'REGISTER.ACC_TYPE',
    CONTINUE = 'REGISTER.CONTINUE',
    ALREADY_ACC = 'REGISTER.ALREADY_ACC',
    LOGIN = 'REGISTER.LOGIN',
    PRIVACY_1 = 'REGISTER.PRIVACY_1',
    TERMS = 'REGISTER.TERMS',
    PRIVACY_2 = 'REGISTER.PRIVACY_2',
    POLICIES = 'REGISTER.POLICIES',
    CAPS_LOCKED_ON = 'REGISTER.CAPS_LOCKED_ON',
    REPEAT_PASSWORD = 'REGISTER.REPEAT_PASSWORD',
    INVITED_TO = 'REGISTER.INVITED_TO',
    RESTORE_PASSWORD = 'REGISTER.RESTORE_PASSWORD',
    EMAIL_ERROR = 'REGISTER.EMAIL_ERROR',
    NAME = 'REGISTER.NAME',
    SURNAME = 'REGISTER.SURNAME',
    NAME_ERROR = 'REGISTER.NAME_ERROR',
    SURNAME_ERROR = 'REGISTER.SURNAME_ERROR'
}

export enum REGISTER_ERRORS {
    EMAIL_FORMAT = 'REGISTER_ERRORS.EMAIL_FORMAT',
    PASSWORD_ERROR = 'REGISTER_ERRORS.PASSWORD_ERROR',
    PASSWORD_MIN = 'REGISTER_ERRORS.PASSWORD_MIN',
    ACCOUNT_TYPE_ERROR = 'REGISTER_ERRORS.ACCOUNT_TYPE_ERROR',
    PRIVACY_POLICY_ERROR = 'REGISTER_ERRORS.PRIVACY_POLICY_ERROR',
    COMPANY_ERROR = 'REGISTER_ERRORS.COMPANY_ERROR',
    REPEAT_PASS_ERROR = 'REGISTER_ERRORS.REPEAT_PASS_ERROR' 
}