export enum USER {
    EDIT = "USER.EDIT",
    ADD = "USER.ADD",
    DELETE = "USER.DELETE"
}

export enum USER_MESSAGES {
    DELETE_MESSAGE = "USER_MESSAGES.DELETE_MESSAGE",
    DELETE_SUCCESS = "USER_MESSAGES.DELETE_SUCCESS",
    EDIT_SUCCESS = "USER_MESSAGES.EDIT_SUCCESS",
    ADD_SUCCESS = "USER_MESSAGES.ADD_SUCCESS",
    CONFIRMATION = "USER_MESSAGES.CONFIRMATION",
    DELETE_NORMAL_USER = "USER_MESSAGES.DELETE_NORMAL_USER",
    PASSWORD_CHECK = "USER_MESSAGES.PASSWORD_CHECK",
    COPIED = "USER_MESSAGES.COPIED"
}

export enum INVITATIONS {
    EMAIL = 'INVITATIONS.EMAIL',
    USED = 'INVITATIONS.USED',
    DATE = 'INVITATIONS.DATE',
    INVITE_USER = 'INVITATIONS.INVITE_USER',
    INVITED_USERS = 'INVITATIONS.INVITED_USERS'
}

export enum INVITATIONS_MESSAGES {
    CANCEL_MESSAGE = "INVITATIONS_MESSAGES.CANCEL_MESSAGE",
    CANCEL_HEADER = "INVITATIONS_MESSAGES.CANCEL_HEADER"
}