version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dontlookatme
      POSTGRES_DB: fathom3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  backend:
    stdin_open: true
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: frontend
    volumes:
       - ./app-ui:/usr/src/app/front
       - /usr/src/app/front/node_modules

volumes:
  postgres-data:
  pgadmin-data: