export enum ModalActions {
  SET_ACCEPT_TEXT = 'SET_ACCEPT_TEXT',
  SET_CANCEL_TEXT = 'SET_CANCEL_TEXT',
  HIDE_CANCEL_BUTTON = 'HIDE_CANCEL_BUTTON',
  HIDE_ACCEPT_BUTTON = 'HIDE_ACCEPT_BUTTON',
  SET_ACCEPT_ENABLED = 'SET_ENABLED',
  SET_WAITING = 'SET_WAITING',
  ACCEPT = 'ACCEPT',
  CLOSE = 'CLOSE',
  SET_TITLE = 'SET_TITLE',
  SET_SUBTITLE = 'SET_SUBTITLE',
}
